// catalog.ts — GENERATED by scripts/generate.ts from openapi.yaml. DO NOT EDIT BY HAND.
// (docs/specs §9) One row per operation. `safe`/`destructive` are hand-curated overlays merged in
// at codegen; the build fails if an operation id is missing from the overlay (fail-closed, §7).

export type OpScope = 'product' | 'developer';

export interface CatalogEntry {
    id: string;
    method: 'GET' | 'POST' | 'PUT' | 'DELETE';
    templatePath: string;
    scope: OpScope;
    summary: string;
    /** true only for read-only allowlisted ops; everything else is write-gated (fail-closed). */
    safe: boolean;
    /** DELETE + known cancel/deactivate POSTs — extra `confirm` guard in MCP. */
    destructive: boolean;
}

// Placeholder until `bun run generate` is implemented (docs/specs §9).
export const catalog: readonly CatalogEntry[] = [];
