// catalog-types.ts — hand-written types for the GENERATED catalog (docs/specs §9).
// catalog.ts (generated by scripts/generate.ts) imports these and exports the op array.

export type OpScope = 'product' | 'developer' | 'other';
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface ParamDef {
    name: string;
    in: 'path' | 'query';
    required: boolean;
    type?: string;
}

export interface CatalogEntry {
    /** OpenAPI operationId, e.g. 'coupons/create'. */
    id: string;
    method: HttpMethod;
    /** Un-interpolated openapi-fetch path, e.g. '/products/{product_id}/coupons.json'. */
    templatePath: string;
    /** product (Bearer-reachable) | developer (out of scope) | other (user scope, etc.). */
    scope: OpScope;
    summary: string;
    /** true only for GET reads; every non-GET is write-gated (fail-closed, §7). */
    safe: boolean;
    /** DELETE + any explicitly-listed destructive write; gated by an extra confirm. */
    destructive: boolean;
    params: ParamDef[];
    /** requestBody (application/json) property names, shallow. */
    requestBodyProps: string[];
}
