// catalog.ts — GENERATED by scripts/generate.ts from openapi.yaml. DO NOT EDIT BY HAND.
// 140 operations. Regenerate with `bun run generate`.

import type { CatalogEntry } from './catalog-types.js';

export const catalog: readonly CatalogEntry[] = [
  {
    "id": "addons/list-plans",
    "method": "GET",
    "templatePath": "/products/{product_id}/addons/{addon_id}/plans.json",
    "scope": "product",
    "summary": "List all plans",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "show_pending",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "type",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "addons/list-plans-features",
    "method": "GET",
    "templatePath": "/products/{product_id}/addons/{addon_id}/plans/{plan_id}/features.json",
    "scope": "product",
    "summary": "List all plan's features",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "addons/list-pricings",
    "method": "GET",
    "templatePath": "/products/{product_id}/addons/{addon_id}/plans/{plan_id}/pricing.json",
    "scope": "product",
    "summary": "List all pricings",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "currency",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "carts/delete",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/carts/{cart_id}.json",
    "scope": "product",
    "summary": "Delete a cart",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "carts/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/carts.json",
    "scope": "product",
    "summary": "List all carts",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "email",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "carts/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/carts/{cart_id}.json",
    "scope": "product",
    "summary": "Retrieve a cart",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "carts/retrieve-events",
    "method": "GET",
    "templatePath": "/products/{product_id}/carts/{cart_id}/events.json",
    "scope": "product",
    "summary": "Retrieve cart events",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "carts/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/carts/{cart_id}.json",
    "scope": "product",
    "summary": "Update a cart",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "plan_id",
      "pricing_id",
      "payment_method",
      "billing_cycle",
      "coupon_id",
      "coupon_code",
      "country_code",
      "vat_id",
      "email",
      "first",
      "last",
      "ip"
    ]
  },
  {
    "id": "coupons/create",
    "method": "POST",
    "templatePath": "/products/{product_id}/coupons.json",
    "scope": "product",
    "summary": "Create a coupon",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "plans",
      "licenses",
      "billing_cycles",
      "user_type",
      "code",
      "discount",
      "discount_type",
      "start_date",
      "end_date",
      "redemptions_limit",
      "has_renewals_discount",
      "has_addons_discount",
      "is_one_per_user",
      "is_active"
    ]
  },
  {
    "id": "coupons/create-note",
    "method": "POST",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/note.json",
    "scope": "product",
    "summary": "Create a note",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "note"
    ]
  },
  {
    "id": "coupons/create-special",
    "method": "PUT",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/special/{special_id}.json",
    "scope": "product",
    "summary": "Create a special coupon",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/delete",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}.json",
    "scope": "product",
    "summary": "Delete a coupon",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/delete-note",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/note.json",
    "scope": "product",
    "summary": "Delete a note",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/delete-special",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/special/{special_id}.json",
    "scope": "product",
    "summary": "Delete a special coupon",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/coupons.json",
    "scope": "product",
    "summary": "List all coupons",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "code",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "prefix",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "coupons/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}.json",
    "scope": "product",
    "summary": "Retrieve a coupon",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/retrieve-note",
    "method": "GET",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/note.json",
    "scope": "product",
    "summary": "Retrieve a note",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "coupons/retrieve-special",
    "method": "GET",
    "templatePath": "/products/{product_id}/coupons/special.json",
    "scope": "product",
    "summary": "Retrieve special coupons",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "type",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "coupons/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}.json",
    "scope": "product",
    "summary": "Update a coupon",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "plans",
      "licenses",
      "billing_cycles",
      "user_type",
      "code",
      "discount",
      "discount_type",
      "start_date",
      "end_date",
      "redemptions_limit",
      "has_renewals_discount",
      "has_addons_discount",
      "is_one_per_user",
      "is_active"
    ]
  },
  {
    "id": "coupons/update-note",
    "method": "PUT",
    "templatePath": "/products/{product_id}/coupons/{coupon_id}/note.json",
    "scope": "product",
    "summary": "Update a note",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "note"
    ]
  },
  {
    "id": "deployments/create",
    "method": "POST",
    "templatePath": "/products/{product_id}/tags.json",
    "scope": "product",
    "summary": "Create a deployment",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "deployments/download",
    "method": "GET",
    "templatePath": "/products/{product_id}/tags/{tag_id}.zip",
    "scope": "product",
    "summary": "Download a deployment",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_premium",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "deployments/download-latest",
    "method": "GET",
    "templatePath": "/products/{product_id}/tags/latest.zip",
    "scope": "product",
    "summary": "Download latest deployment",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_premium",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "deployments/get-latest",
    "method": "GET",
    "templatePath": "/products/{product_id}/tags/latest.json",
    "scope": "product",
    "summary": "Get latest deployment",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_premium",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "deployments/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/tags.json",
    "scope": "product",
    "summary": "List all deployments",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "deployments/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/tags/{tag_id}.json",
    "scope": "product",
    "summary": "Update a deployment",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "release_mode",
      "limit",
      "percentage_limit",
      "is_incremental"
    ]
  },
  {
    "id": "developers/add-team-member",
    "method": "POST",
    "templatePath": "/developer/{developer_id}/products/{product_id}/installs/{install_id}/members.json",
    "scope": "other",
    "summary": "Add team member",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "role",
      "member_id",
      "email"
    ]
  },
  {
    "id": "developers/log-in",
    "method": "POST",
    "templatePath": "/developers/{developer_id}/login.json",
    "scope": "developer",
    "summary": "Log in",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "email",
      "password",
      "recaptcha_token",
      "remember_me",
      "code",
      "backup_code"
    ]
  },
  {
    "id": "developers/retrieve-bank-account",
    "method": "GET",
    "templatePath": "/developers/{developer_id}/bank_account/{bank_account_id}.json",
    "scope": "developer",
    "summary": "Retrieve bank account",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "events/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/events.json",
    "scope": "product",
    "summary": "List all events",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "state",
        "in": "query",
        "required": false
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "events/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/events/{event_id}.json",
    "scope": "product",
    "summary": "Retrieve an event",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/activate-license",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Activate a license",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "license_key",
        "in": "query",
        "required": true,
        "type": "string"
      },
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/cancel-trial",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/installs/{install_id}/trials.json",
    "scope": "product",
    "summary": "Cancel a trial",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "reason_ids",
        "in": "query",
        "required": false,
        "type": "array"
      },
      {
        "name": "reason",
        "in": "query",
        "required": false
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/change-ownership",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/users/{user_id}/ownership-change.json",
    "scope": "product",
    "summary": "Change ownership",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "token_salt",
      "email",
      "transfer_type",
      "owner_token",
      "candidate_token",
      "after_confirm_url",
      "install_ids"
    ]
  },
  {
    "id": "installations/create-clone",
    "method": "POST",
    "templatePath": "/products/{product_id}/installs/{install_id}/clones.json",
    "scope": "product",
    "summary": "Create a clone",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "site_url"
    ]
  },
  {
    "id": "installations/create-new-license",
    "method": "POST",
    "templatePath": "/products/{product_id}/installs/{install_id}/plans/{plan_id}/pricing/{pricing_id}/licenses.json",
    "scope": "product",
    "summary": "Create a new license",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "is_block_features",
      "period",
      "expires_at",
      "send_email"
    ]
  },
  {
    "id": "installations/deactivate-license",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/installs/{install_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Deactivate a license",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "license_key",
        "in": "query",
        "required": true,
        "type": "string"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/delete-install",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/installs/{install_id}.json",
    "scope": "product",
    "summary": "Delete an install",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "installations/downgrade-default-plan",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/downgrade.json",
    "scope": "product",
    "summary": "Downgrade to the default plan",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "deactivate_license",
      "reason_ids",
      "reason"
    ]
  },
  {
    "id": "installations/list-active-licenses",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/licenses.json",
    "scope": "product",
    "summary": "List all active licenses",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-events",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/events.json",
    "scope": "product",
    "summary": "List all events",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-installs",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs.json",
    "scope": "product",
    "summary": "List all installs",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "ids",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "version",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "license_id",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "plan_id",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "title",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "url",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "all",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "reason_id",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-market-items",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/market_items.json",
    "scope": "product",
    "summary": "List all market items",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-payments",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/payments.json",
    "scope": "product",
    "summary": "List all payments",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "extended",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-plans",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/plans.json",
    "scope": "product",
    "summary": "List all plans",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "show_pending",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-plans-features-for-addon",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/addons/{addon_id}/plans/{plan_id}/features.json",
    "scope": "product",
    "summary": "List all plan's features for Addon",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/list-updates",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/updates.json",
    "scope": "product",
    "summary": "List all updates",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "version",
        "in": "query",
        "required": true,
        "type": "string"
      },
      {
        "name": "older_than",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/resolve-clone",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/clones/{clone_id}.json",
    "scope": "product",
    "summary": "Resolve a clone",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "resolution",
      "new_install_id"
    ]
  },
  {
    "id": "installations/retrieve-active-license-by-id",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Retrieve an active license by ID",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "license_key",
        "in": "query",
        "required": true
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-active-license-by-uid",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/license.json",
    "scope": "product",
    "summary": "Retrieve an active license by UID",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "license_key",
        "in": "query",
        "required": true
      },
      {
        "name": "uid",
        "in": "query",
        "required": true,
        "type": "string"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-install",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}.json",
    "scope": "product",
    "summary": "Retrieve an install",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-installs-count",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/count.json",
    "scope": "product",
    "summary": "Retrieve installs count",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "plan_id",
        "in": "query",
        "required": false,
        "type": "number"
      },
      {
        "name": "is_active",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-latest-update",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/updates/latest.json",
    "scope": "product",
    "summary": "Retrieve the latest update",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_premium",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "readme",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "newer_than",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-plan",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/plans/{plan_id}.json",
    "scope": "product",
    "summary": "Retrieve a plan",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/retrieve-uninstall-details",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/uninstall.json",
    "scope": "product",
    "summary": "Retrieve uninstall details",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "installations/send-verification-email",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/users/{user_id}/verify.json",
    "scope": "product",
    "summary": "Send a verification email",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "after_email_confirm_url"
    ]
  },
  {
    "id": "installations/start-trial",
    "method": "POST",
    "templatePath": "/products/{product_id}/installs/{install_id}/plans/{plan_id}/trials.json",
    "scope": "product",
    "summary": "Start a trial",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "trial_ends",
      "phone",
      "is_migration",
      "trial_token",
      "trial_timestamp"
    ]
  },
  {
    "id": "installations/uninstall-from-anonymous-site",
    "method": "PUT",
    "templatePath": "/products/{product_id}/uninstall.json",
    "scope": "product",
    "summary": "Uninstall from anonymous site",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "uid",
      "reason_id",
      "reason"
    ]
  },
  {
    "id": "installations/update-install",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}.json",
    "scope": "product",
    "summary": "Update an install",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "uid",
      "license_key",
      "url",
      "title",
      "version",
      "sdk_version",
      "platform_version",
      "programming_language_version",
      "plan_id",
      "trial_plan_id",
      "trials_ends",
      "subscription_id",
      "is_locked",
      "is_active",
      "is_disconnected",
      "is_premium",
      "is_sdk_required",
      "reason_id",
      "reason_info",
      "plugins",
      "themes",
      "is_beta",
      "recover",
      "is_uninstalled",
      "user_id",
      "user_email",
      "install_ids"
    ]
  },
  {
    "id": "installations/update-permissions",
    "method": "PUT",
    "templatePath": "/products/{product_id}/installs/{install_id}/permissions.json",
    "scope": "product",
    "summary": "Update permissions",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "is_enabled",
      "permissions"
    ]
  },
  {
    "id": "licenses/activate",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/activate.json",
    "scope": "product",
    "summary": "Activate a license",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "uid",
      "license_key",
      "url",
      "title",
      "version",
      "is_marketing_allowed",
      "install_id",
      "first_name",
      "last_name",
      "user_email",
      "allow_unreleased_plan_activation"
    ]
  },
  {
    "id": "licenses/assign",
    "method": "PUT",
    "templatePath": "/products/{product_id}/licenses.json",
    "scope": "product",
    "summary": "Assign a license",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "email",
      "name",
      "license_key",
      "is_marketing_allowed"
    ]
  },
  {
    "id": "licenses/cancel",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Cancel a license",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "delete",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "include_bundle",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/cancel-current-subscription",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/licenses/{license_id}/subscription.json",
    "scope": "product",
    "summary": "Cancel current subscription",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "reason_ids",
        "in": "query",
        "required": false,
        "type": "array"
      },
      {
        "name": "reason",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/create-review",
    "method": "POST",
    "templatePath": "/products/{product_id}/users/{user_id}/licenses/{license_id}/reviews.json",
    "scope": "product",
    "summary": "Create a review",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "rate",
      "title",
      "text",
      "name",
      "job_title",
      "company",
      "company_url",
      "profile_url",
      "is_active"
    ]
  },
  {
    "id": "licenses/deactivate",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/deactivate.json",
    "scope": "product",
    "summary": "Deactivate a license",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "uid",
      "install_id",
      "license_key"
    ]
  },
  {
    "id": "licenses/deactivate-installs",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/licenses/{license_id}/installs.json",
    "scope": "product",
    "summary": "Deactivate installs",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/generate-upgrade-link",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/{license_id}/checkout/link.json",
    "scope": "product",
    "summary": "Generate upgrade link",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "plan_id",
      "billing_cycle",
      "quota",
      "is_payment_method_update"
    ]
  },
  {
    "id": "licenses/get-review-url",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/licenses/{license_id}/review_url.json",
    "scope": "product",
    "summary": "Get review URL",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "licenses/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/licenses.json",
    "scope": "product",
    "summary": "List all licenses",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "plan_id",
        "in": "query",
        "required": false,
        "type": "number"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "source",
        "in": "query",
        "required": false,
        "type": "number"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/list-subscriptions",
    "method": "GET",
    "templatePath": "/products/{product_id}/installs/{install_id}/licenses/{license_id}/subscriptions.json",
    "scope": "product",
    "summary": "List all subscriptions",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/resend-keys",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/resend.json",
    "scope": "product",
    "summary": "Resend license keys",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "email"
    ]
  },
  {
    "id": "licenses/resend-upgrade-email",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/{license_id}/resend.json",
    "scope": "product",
    "summary": "Resend the upgrade email",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "licenses/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Retrieve a license",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/retrieve-latest-subscription",
    "method": "GET",
    "templatePath": "/products/{product_id}/licenses/{license_id}/subscription.json",
    "scope": "product",
    "summary": "Retrieve latest subscription",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/send-renewal-email",
    "method": "POST",
    "templatePath": "/products/{product_id}/licenses/{license_id}/renewals.json",
    "scope": "product",
    "summary": "Send the renewal email",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "licenses/sync-activations",
    "method": "POST",
    "templatePath": "/developers/{developer_id}/products/{product_id}/licenses/{license_id}/installs/sync.json",
    "scope": "developer",
    "summary": "Sync all activations",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "licenses/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/licenses/{license_id}.json",
    "scope": "product",
    "summary": "Update a license",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "quota",
      "expiration",
      "is_block_features",
      "is_whitelabeled",
      "is_free_localhost",
      "new_user_id",
      "cancel_subscription",
      "extend_bundle",
      "update_subscription_renewal_date"
    ]
  },
  {
    "id": "payments/download-invoice",
    "method": "GET",
    "templatePath": "/products/{product_id}/payments/{payment_id}/invoice.pdf",
    "scope": "product",
    "summary": "Download invoice",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "payments/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/payments.json",
    "scope": "product",
    "summary": "List all payments",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "search_user_id",
        "in": "query",
        "required": false
      },
      {
        "name": "billing_cycle",
        "in": "query",
        "required": false
      },
      {
        "name": "currency",
        "in": "query",
        "required": false
      },
      {
        "name": "coupon_id",
        "in": "query",
        "required": false
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "extended",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "to",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "from",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "payments/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/payments/{payment_id}.json",
    "scope": "product",
    "summary": "Retrieve a payment",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/clone-pricing-other-currency",
    "method": "POST",
    "templatePath": "/products/{product_id}/plans/{plan_id}/pricing/clone.json",
    "scope": "product",
    "summary": "Clone pricing to other currency",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "to_currency",
      "from_currency"
    ]
  },
  {
    "id": "plans/create",
    "method": "POST",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans.json",
    "scope": "developer",
    "summary": "Create a plan",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "developer_id",
        "in": "path",
        "required": true,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "name",
      "title",
      "description",
      "is_free_localhost",
      "is_block_features",
      "is_block_features_monthly",
      "license_type",
      "trial_period",
      "is_require_subscription",
      "support_forum",
      "support_kb",
      "support_email",
      "support_phone",
      "is_success_manager",
      "is_featured"
    ]
  },
  {
    "id": "plans/create-license",
    "method": "POST",
    "templatePath": "/products/{product_id}/plans/{plan_id}/pricing/{pricing_id}/licenses.json",
    "scope": "product",
    "summary": "Create a license",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "is_whitelabeled",
      "period",
      "is_block_features",
      "expires_at",
      "email",
      "existing_install_id",
      "send_email",
      "source",
      "license_key"
    ]
  },
  {
    "id": "plans/create-pricing",
    "method": "POST",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans/{plan_id}/pricing.json",
    "scope": "developer",
    "summary": "Create a pricing",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "currency",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": [
      "monthly_price",
      "annual_price",
      "lifetime_price",
      "licenses",
      "currency"
    ]
  },
  {
    "id": "plans/delete",
    "method": "DELETE",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans/{plan_id}.json",
    "scope": "developer",
    "summary": "Delete a plan",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "developer_id",
        "in": "path",
        "required": true,
        "type": "integer"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/delete-s-pricing",
    "method": "DELETE",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans/{plan_id}/pricing/{pricing_id}.json",
    "scope": "developer",
    "summary": "Delete a plan's pricing",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "plans/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans.json",
    "scope": "product",
    "summary": "List all plans",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/list-currencies",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans/currencies.json",
    "scope": "product",
    "summary": "List all currencies",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "plans/list-features",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans/{plan_id}/features.json",
    "scope": "product",
    "summary": "List all features",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/list-s-pricing",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans/{plan_id}/pricing.json",
    "scope": "product",
    "summary": "List all plan's pricing",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "currency",
        "in": "query",
        "required": false
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans/{plan_id}.json",
    "scope": "product",
    "summary": "Retrieve a plan",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/retrieve-pricing",
    "method": "GET",
    "templatePath": "/products/{product_id}/plans/{plan_id}/pricing/{pricing_id}.json",
    "scope": "product",
    "summary": "Retrieve a pricing",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "plans/update",
    "method": "PUT",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans/{plan_id}.json",
    "scope": "developer",
    "summary": "Update a plan",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "developer_id",
        "in": "path",
        "required": true,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "name",
      "title",
      "description",
      "is_free_localhost",
      "is_block_features",
      "is_block_features_monthly",
      "license_type",
      "trial_period",
      "is_require_subscription",
      "support_forum",
      "support_kb",
      "support_email",
      "support_phone",
      "is_success_manager",
      "is_featured",
      "is_hidden"
    ]
  },
  {
    "id": "plans/update-pricing",
    "method": "PUT",
    "templatePath": "/developers/{developer_id}/products/{product_id}/plans/{plan_id}/pricing/{pricing_id}.json",
    "scope": "developer",
    "summary": "Update a pricing",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "products/check-status",
    "method": "GET",
    "templatePath": "/products/{product_id}/is_active.json",
    "scope": "product",
    "summary": "Check product status",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "is_update",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/delete-email-addresses",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/emails/addresses.json",
    "scope": "product",
    "summary": "Delete all email addresses",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "products/delete-feature",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/features/{feature_id}.json",
    "scope": "product",
    "summary": "Delete a feature",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "products/delete-setting",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/settings/{setting_id}.json",
    "scope": "product",
    "summary": "Delete a setting",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "products/gdpr-compliance-check",
    "method": "GET",
    "templatePath": "/products/{product_id}/ping.json",
    "scope": "product",
    "summary": "GDPR compliance check",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "uid",
        "in": "query",
        "required": true
      },
      {
        "name": "is_update",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "is_gdpr_test",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/generate-portal-login-link",
    "method": "POST",
    "templatePath": "/products/{product_id}/portal/login.json",
    "scope": "product",
    "summary": "Generate portal login link",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "id",
      "email"
    ]
  },
  {
    "id": "products/get-info",
    "method": "GET",
    "templatePath": "/products/{product_id}/info.json",
    "scope": "product",
    "summary": "Get product info",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/list-addons",
    "method": "GET",
    "templatePath": "/products/{product_id}/addons.json",
    "scope": "product",
    "summary": "List all addons",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "show_pending",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/list-email-addresses",
    "method": "GET",
    "templatePath": "/products/{product_id}/emails/addresses.json",
    "scope": "product",
    "summary": "List all email addresses",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/list-features",
    "method": "GET",
    "templatePath": "/products/{product_id}/features.json",
    "scope": "product",
    "summary": "List all features",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}.json",
    "scope": "other",
    "summary": "Retrieve a product",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/retrieve-feature",
    "method": "GET",
    "templatePath": "/products/{product_id}/features/{feature_id}.json",
    "scope": "product",
    "summary": "Retrieve a feature",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/retrieve-pricing-table-data",
    "method": "GET",
    "templatePath": "/products/{product_id}/pricing.json",
    "scope": "product",
    "summary": "Retrieve the pricing table data",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "currency",
        "in": "query",
        "required": false
      },
      {
        "name": "show_pending",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "type",
        "in": "query",
        "required": false
      },
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "bundle_product_id",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "bundle_product_public_key",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/retrieve-setting",
    "method": "GET",
    "templatePath": "/products/{product_id}/settings/{setting_id}.json",
    "scope": "product",
    "summary": "Retrieve a setting",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "products/skip-account-connection",
    "method": "PUT",
    "templatePath": "/products/{product_id}/skip.json",
    "scope": "product",
    "summary": "Skip account connection",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "uids",
      "uid"
    ]
  },
  {
    "id": "products/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}.json",
    "scope": "other",
    "summary": "Update a product",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "slug",
      "title",
      "type",
      "plans",
      "features",
      "money_back_period",
      "refund_policy",
      "annual_renewals_discount",
      "renewals_discount_type",
      "lifetime_license_proration_days",
      "is_pricing_visible",
      "default_plan_id",
      "accepted_payments",
      "expose_license_key",
      "enable_after_purchase_email_login_link"
    ]
  },
  {
    "id": "products/update-email-addressses",
    "method": "PUT",
    "templatePath": "/developers/{developer_id}/products/{product_id}/emails/addresses.json",
    "scope": "developer",
    "summary": "Update email addressses",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "products/update-feature",
    "method": "PUT",
    "templatePath": "/products/{product_id}/features/{feature_id}.json",
    "scope": "product",
    "summary": "Update a feature",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "title",
      "description",
      "is_featured"
    ]
  },
  {
    "id": "products/update-setting",
    "method": "PUT",
    "templatePath": "/products/{product_id}/settings/{setting_id}.json",
    "scope": "product",
    "summary": "Update a setting",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "data"
    ]
  },
  {
    "id": "reviews/create",
    "method": "POST",
    "templatePath": "/products/{product_id}/reviews.json",
    "scope": "product",
    "summary": "Create a review",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "title",
      "text",
      "name",
      "rate",
      "job_title",
      "company",
      "company_url",
      "profile_url",
      "is_featured",
      "is_active"
    ]
  },
  {
    "id": "reviews/delete",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/reviews/{review_id}.json",
    "scope": "product",
    "summary": "Delete a review",
    "safe": false,
    "destructive": true,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "reviews/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/reviews.json",
    "scope": "product",
    "summary": "List all reviews",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "reviews/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/reviews/{review_id}.json",
    "scope": "product",
    "summary": "Retrieve a review",
    "safe": true,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "reviews/retrieve-summary",
    "method": "GET",
    "templatePath": "/products/{product_id}/reviews/summary.json",
    "scope": "product",
    "summary": "Retrieve reviews summary",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "reviews/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/reviews/{review_id}.json",
    "scope": "product",
    "summary": "Update a review",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "title",
      "text",
      "name",
      "rate",
      "job_title",
      "company",
      "company_url",
      "profile_url",
      "is_featured"
    ]
  },
  {
    "id": "subscriptions/cancel",
    "method": "DELETE",
    "templatePath": "/products/{product_id}/subscriptions/{subscription_id}.json",
    "scope": "product",
    "summary": "Cancel a subscription",
    "safe": false,
    "destructive": true,
    "params": [
      {
        "name": "reason_ids",
        "in": "query",
        "required": false,
        "type": "array"
      },
      {
        "name": "reason",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "subscriptions/create-new-migrated-payment",
    "method": "POST",
    "templatePath": "/products/{product_id}/subscriptions/{subscription_id}/payments.json",
    "scope": "product",
    "summary": "Create a new migrated payment",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "gross",
      "payment_external_id",
      "source",
      "vat",
      "gateway_fee",
      "processed_at",
      "is_extend_license",
      "next_payment"
    ]
  },
  {
    "id": "subscriptions/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/subscriptions.json",
    "scope": "product",
    "summary": "List all subscriptions",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "billing_cycle",
        "in": "query",
        "required": false
      },
      {
        "name": "gateway",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "extended",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "enrich_with_cancellation_discounts",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "subscriptions/list-payments",
    "method": "GET",
    "templatePath": "/products/{product_id}/subscriptions/{subscription_id}/payments.json",
    "scope": "product",
    "summary": "List all payments",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "subscriptions/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/subscriptions/{subscription_id}.json",
    "scope": "product",
    "summary": "Retrieve a subscription",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "subscriptions/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/subscriptions/{subscription_id}.json",
    "scope": "product",
    "summary": "Update a subscription",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": [
      "coupon_id"
    ]
  },
  {
    "id": "trials/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/trials.json",
    "scope": "product",
    "summary": "List all trials",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "from",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "to",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/create",
    "method": "POST",
    "templatePath": "/products/{product_id}/users.json",
    "scope": "product",
    "summary": "Create a user",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "email",
      "password",
      "ip",
      "name",
      "first",
      "last",
      "picture",
      "is_verified",
      "after_email_confirm_url",
      "send_verification_email",
      "is_marketing_allowed",
      "is_migration",
      "source"
    ]
  },
  {
    "id": "users/create-checkout-token",
    "method": "POST",
    "templatePath": "/products/{product_id}/users/{user_id}/tokens/checkout.json",
    "scope": "product",
    "summary": "Create a checkout token",
    "safe": false,
    "destructive": false,
    "params": [],
    "requestBodyProps": []
  },
  {
    "id": "users/download-invoice",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/payments/{payment_id}/invoice.pdf",
    "scope": "product",
    "summary": "Download invoice",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list",
    "method": "GET",
    "templatePath": "/products/{product_id}/users.json",
    "scope": "product",
    "summary": "List all users",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "email",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list-events",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/events.json",
    "scope": "product",
    "summary": "List all events",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list-installs",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/installs.json",
    "scope": "product",
    "summary": "List all installs",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "install_ids",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "license_id",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "plan_id",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list-licenses",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/licenses.json",
    "scope": "product",
    "summary": "List all licenses",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "license_key",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "ids",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "license_keys",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "type",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "is_enriched",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list-payments",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/payments.json",
    "scope": "product",
    "summary": "List all payments",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "extended",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "include_addons",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "include_bundles",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "billing_cycle",
        "in": "query",
        "required": false
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/list-subscriptions",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/subscriptions.json",
    "scope": "product",
    "summary": "List all subscriptions",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "extended",
        "in": "query",
        "required": false,
        "type": "boolean"
      },
      {
        "name": "filter",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "billing_cycle",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "gateway",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "count",
        "in": "query",
        "required": false,
        "type": "integer"
      },
      {
        "name": "plan_id",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "search",
        "in": "query",
        "required": false,
        "type": "string"
      },
      {
        "name": "enrich_with_cancellation_discounts",
        "in": "query",
        "required": false,
        "type": "boolean"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/retrieve",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}.json",
    "scope": "product",
    "summary": "Retrieve a user",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/retrieve-billing",
    "method": "GET",
    "templatePath": "/products/{product_id}/users/{user_id}/billing.json",
    "scope": "product",
    "summary": "Retrieve billing",
    "safe": true,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": []
  },
  {
    "id": "users/update",
    "method": "PUT",
    "templatePath": "/products/{product_id}/users/{user_id}.json",
    "scope": "product",
    "summary": "Update a user",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "fields",
        "in": "query",
        "required": false,
        "type": "string"
      }
    ],
    "requestBodyProps": [
      "name",
      "first",
      "last",
      "is_marketing_allowed",
      "is_beta"
    ]
  },
  {
    "id": "users/update-or-create-billing",
    "method": "PUT",
    "templatePath": "/products/{product_id}/users/{user_id}/billing.json",
    "scope": "product",
    "summary": "Update or create billing",
    "safe": false,
    "destructive": false,
    "params": [
      {
        "name": "product_id",
        "in": "path",
        "required": true,
        "type": "integer"
      },
      {
        "name": "user_id",
        "in": "path",
        "required": true,
        "type": "integer"
      }
    ],
    "requestBodyProps": [
      "business_name",
      "first",
      "last",
      "email",
      "phone",
      "website",
      "tax_id",
      "address_street",
      "address_apt",
      "address_city",
      "address_country",
      "address_country_code",
      "address_state",
      "address_zip"
    ]
  }
];
