// validators.ts — GENERATED by scripts/generate.ts from openapi.yaml. DO NOT EDIT BY HAND.
// Runtime param validation per operation (docs/specs §9). Must resolve to the workspace's zod v4
// (or ajv if the zod-v4 generator isn't proven). Acceptance bar: round-trips a sample payload.

import type { z } from 'zod';

// Placeholder until `bun run generate` is implemented (docs/specs §9).
export const validators: Record<string, z.ZodTypeAny> = {};
