// build-ui.ts — bundle the iframe apps (target:browser) into self-contained HTML strings,
// emitted as GENERATED TS modules that the MCP server imports. Run: `bun run generate:ui`.

async function buildApp(options: {
    entry: string;
    out: string;
    marker: string;
    title: string;
    css: string;
    bodyHtml: string;
    variableName: string;
}) {
    const result = await Bun.build({
        entrypoints: [options.entry],
        target: 'browser',
        format: 'esm',
        minify: true,
    });
    if (!result.success) {
        for (const log of result.logs) {
            console.error(log);
        }
        process.exit(1);
    }

    const output = result.outputs[0];
    if (!output) {
        throw new Error(`No build output found for ${options.entry}`);
    }
    const js = await output.text();

    const html =
        '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
        '<meta name="viewport" content="width=device-width,initial-scale=1">' +
        `<title>${options.title}</title><style>${options.css}</style></head>` +
        `<body data-app="${options.marker}">` +
        options.bodyHtml +
        `<script type="module">${js}</script></body></html>`;

    const banner =
        '// GENERATED by scripts/build-ui.ts — DO NOT EDIT. Run `bun run generate:ui` to regenerate.\n' +
        `// The self-contained ${options.title} MCP App (HTML + inlined, minified, browser-bundled JS).\n`;

    await Bun.write(options.out, `${banner}export const ${options.variableName} = ${JSON.stringify(html)};\n`);
    console.log(`Wrote ${options.out} (${html.length} bytes)`);
}

// --- Revenue Dashboard Config ---
const REVENUE_CSS = [
    ':root{color-scheme:light dark;font-family:system-ui,sans-serif}',
    'body{margin:0;padding:16px;line-height:1.4}',
    'nav.windows{display:flex;gap:8px;margin-bottom:12px}',
    'nav.windows button{padding:4px 12px;border-radius:6px;border:1px solid currentColor;background:transparent;cursor:pointer;font:inherit}',
    'header .window{font-size:12px;opacity:.7}',
    'p.flags{color:#b45309;font-size:13px;margin:8px 0}',
    'p.empty{opacity:.6}',
    '.cards{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}',
    '.card{border:1px solid rgba(128,128,128,.3);border-radius:10px;padding:12px 14px}',
    '.card h2{margin:0 0 10px;font-size:16px}.card h2 small{opacity:.6;font-weight:400;font-size:12px}',
    '.bar-row{display:grid;grid-template-columns:64px 1fr 80px;align-items:center;gap:8px;margin:4px 0;font-size:13px}',
    '.bar{height:8px;background:rgba(128,128,128,.18);border-radius:4px;overflow:hidden}',
    '.bar-fill{display:block;height:100%}',
    '.bar-fill.gross{background:#2563eb}.bar-fill.refunds{background:#dc2626}.bar-fill.net{background:#16a34a}',
    '.bar-val{text-align:right;font-variant-numeric:tabular-nums}',
].join('');

const REVENUE_BODY =
    '<nav class="windows"><button data-days="30">30d</button>' +
    '<button data-days="90">90d</button><button data-days="365">365d</button></nav>' +
    '<main id="root"><p class="empty">Loading…</p></main>';

// --- Coupon Form Config ---
const COUPON_CSS = [
    ':root{color-scheme:light dark;font-family:system-ui,-apple-system,sans-serif;',
    '--bg:#121214;--card-bg:#1c1c1f;--border:rgba(255,255,255,0.08);',
    '--text:#f3f4f6;--text-muted:#9ca3af;--primary:#3b82f6;--primary-hover:#2563eb;',
    '--success:#10b981;--error:#ef4444;--highlight:rgba(59,130,246,0.1);--hover-bg:rgba(255,255,255,0.03)}',
    '@media (prefers-color-scheme:light){:root{',
    '--bg:#f9fafb;--card-bg:#ffffff;--border:rgba(0,0,0,0.08);',
    '--text:#111827;--text-muted:#6b7280;--primary:#2563eb;--primary-hover:#1d4ed8;',
    '--highlight:rgba(37,99,235,0.06);--hover-bg:rgba(0,0,0,0.02)}}',
    'body{margin:0;padding:16px;background-color:var(--bg);color:var(--text);',
    'display:flex;justify-content:center;align-items:flex-start}',
    '.app-container{display:flex;flex-direction:column;gap:20px;width:100%;max-width:480px;box-sizing:border-box}',
    '.coupon-form-card{background:var(--card-bg);border:1px solid var(--border);',
    'border-radius:12px;padding:24px;width:100%;box-shadow:0 4px 12px rgba(0,0,0,0.15);box-sizing:border-box;',
    'transition:transform 0.2s ease,box-shadow 0.2s ease}',
    'h2{margin:0 0 20px;font-size:18px;font-weight:600;display:flex;align-items:center;gap:8px}',
    '.form-group{margin-bottom:16px}',
    '.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}',
    'label{display:block;font-size:12px;font-weight:600;margin-bottom:6px;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.05em}',
    'input[type="text"],input[type="number"],select{width:100%;padding:10px 12px;',
    'border-radius:6px;border:1px solid var(--border);background:var(--card-bg);',
    'color:var(--text);font-family:inherit;font-size:14px;box-sizing:border-box;',
    'transition:border-color 0.15s ease,box-shadow 0.15s ease}',
    'input:focus,select:focus{outline:none;border-color:var(--primary);',
    'box-shadow:0 0 0 3px rgba(59,130,246,0.15)}',
    '.plans-status{font-size:13px;color:var(--text-muted);font-style:italic;padding:8px 0;text-align:center}',
    '.plans-checkboxes{max-height:120px;overflow-y:auto;border:1px solid var(--border);',
    'border-radius:6px;padding:8px 12px;display:flex;flex-direction:column;gap:8px}',
    '.plan-option{display:flex;align-items:center;gap:8px;font-size:13px;color:var(--text);cursor:pointer}',
    '.plan-option input{margin:0;cursor:pointer}',
    'button[type="submit"],.primary-btn{width:100%;padding:12px;border:none;border-radius:6px;',
    'background-color:var(--primary);color:white;font-size:14px;font-weight:600;',
    'cursor:pointer;transition:background-color 0.15s ease;margin-top:8px;display:flex;justify-content:center;align-items:center;gap:6px}',
    'button[type="submit"]:hover:not(:disabled),.primary-btn:hover{background-color:var(--primary-hover)}',
    'button[type="submit"]:disabled{opacity:0.6;cursor:not-allowed}',
    '.secondary-btn{width:100%;padding:10px;border:1px solid var(--border);border-radius:6px;',
    'background:transparent;color:var(--text);font-size:14px;font-weight:600;',
    'cursor:pointer;transition:background-color 0.15s ease;margin-top:12px;display:flex;justify-content:center;align-items:center;gap:6px}',
    '.secondary-btn:hover{background-color:var(--hover-bg)}',
    '.result{margin-top:16px;padding:12px;border-radius:6px;font-size:13px;display:none;animation:fadeIn 0.2s ease-in-out}',
    '.result.success{background:rgba(16, 185, 129, 0.1);border:1px solid var(--success);color:var(--success)}',
    '.result.error{background:rgba(239, 68, 68, 0.1);border:1px solid var(--error);color:var(--error)}',
    '.success-state{text-align:center;animation:scaleUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)}',
    '.success-icon-wrap{width:48px;height:48px;border-radius:50%;background:rgba(16,185,129,0.1);color:var(--success);',
    'display:flex;align-items:center;justify-content:center;margin:0 auto 16px}',
    '.success-code-box{background:var(--highlight);border:1px dashed var(--primary);border-radius:8px;',
    'padding:16px;margin:16px 0;display:flex;align-items:center;justify-content:space-between;gap:12px}',
    '.success-code{font-family:monospace;font-size:20px;font-weight:700;color:var(--primary);letter-spacing:0.05em}',
    '.copy-badge-btn{padding:6px 12px;border-radius:6px;border:none;background:var(--primary);color:white;',
    'font-size:12px;font-weight:600;cursor:pointer;display:flex;align-items:center;gap:4px;transition:opacity 0.2s}',
    '.copy-badge-btn:hover{opacity:0.9}',
    '.success-details{border-top:1px solid var(--border);padding-top:14px;margin-top:14px;display:flex;flex-direction:column;gap:8px}',
    '.detail-row{display:flex;justify-content:space-between;font-size:13px}',
    '.detail-lbl{color:var(--text-muted)}',
    '.detail-val{font-weight:600}',
    '.list-card{padding:20px 24px}',
    '.list-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}',
    '.list-header h2{margin:0}',
    '.icon-btn{background:transparent;border:none;border-radius:50%;width:32px;height:32px;',
    'color:var(--text-muted);cursor:pointer;display:flex;align-items:center;justify-content:center;',
    'transition:background-color 0.2s,color 0.2s}',
    '.icon-btn:hover{background-color:var(--hover-bg);color:var(--text)}',
    '.coupons-list{display:flex;flex-direction:column;gap:10px;max-height:220px;overflow-y:auto}',
    '.coupon-item{display:flex;justify-content:space-between;align-items:center;padding:10px 12px;',
    'border:1px solid var(--border);border-radius:8px;background:rgba(128,128,128,0.02);',
    'transition:background-color 0.15s}',
    '.coupon-item:hover{background:var(--hover-bg)}',
    '.coupon-item-info{display:flex;flex-direction:column;gap:4px}',
    '.coupon-item-code{font-family:monospace;font-weight:700;font-size:14px;color:var(--text)}',
    '.coupon-item-meta{font-size:11px;color:var(--text-muted);display:flex;gap:8px;align-items:center}',
    '.coupon-item-actions{display:flex;align-items:center;gap:8px}',
    '.badge-discount{background:rgba(16,185,129,0.1);color:var(--success);font-size:11px;',
    'font-weight:600;padding:2px 6px;border-radius:4px}',
    '.badge-active{width:6px;height:6px;border-radius:50%;background-color:var(--success)}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}',
    '@keyframes scaleUp{from{opacity:0;transform:scale(0.95)}to{opacity:1;transform:scale(1)}}',
].join('');

const COUPON_BODY =
    '<div class="app-container">' +
    '<!-- Success State (hidden) -->' +
    '<div id="success-card" class="coupon-form-card success-state" style="display:none;">' +
    '<div class="success-icon-wrap">' +
    '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>' +
    '</div>' +
    '<h2>Coupon Created!</h2>' +
    '<div class="success-code-box">' +
    '<span id="success-code-val" class="success-code"></span>' +
    '<button id="copy-btn" class="copy-badge-btn">' +
    '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>' +
    'Copy' +
    '</button>' +
    '</div>' +
    '<div class="success-details">' +
    '<div class="detail-row"><span class="detail-lbl">Discount</span><span id="success-discount-val" class="detail-val"></span></div>' +
    '<div class="detail-row"><span class="detail-lbl">Applies to</span><span id="success-plans-val" class="detail-val"></span></div>' +
    '<div class="detail-row"><span class="detail-lbl">Coupon ID</span><span id="success-id-val" class="detail-val"></span></div>' +
    '</div>' +
    '<button id="reset-btn" class="secondary-btn">Create Another Coupon</button>' +
    '</div>' +
    '<!-- Form Card -->' +
    '<form id="coupon-form" class="coupon-form-card">' +
    '<h2>Create Coupon</h2>' +
    '<div class="form-group">' +
    '<label for="code">Coupon Code</label>' +
    '<input type="text" id="code" name="code" placeholder="e.g., SAVE50" required autocomplete="off" />' +
    '</div>' +
    '<div class="form-row">' +
    '<div class="form-group">' +
    '<label for="discount">Discount Amount</label>' +
    '<input type="number" id="discount" name="discount" step="any" min="0" placeholder="0" required />' +
    '</div>' +
    '<div class="form-group">' +
    '<label for="discount-type">Discount Type</label>' +
    '<select id="discount-type" name="discount_type">' +
    '<option value="percentage">Percentage (%)</option>' +
    '<option value="dollar">Dollar ($)</option>' +
    '</select>' +
    '</div>' +
    '</div>' +
    '<div class="form-group">' +
    '<label>Applies to Plans</label>' +
    '<div id="plans-loading" class="plans-status">Loading plans...</div>' +
    '<div id="plans-container" class="plans-checkboxes"></div>' +
    '</div>' +
    '<button type="submit" id="submit-btn">Create Coupon</button>' +
    '<div id="result" class="result"></div>' +
    '</form>' +
    '<!-- Recent Coupons Card -->' +
    '<div class="coupon-form-card list-card">' +
    '<div class="list-header">' +
    '<h2>Recent Coupons</h2>' +
    '<button id="refresh-list-btn" class="icon-btn" title="Refresh list">' +
    '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"></path></svg>' +
    '</button>' +
    '</div>' +
    '<div id="coupons-loading" class="plans-status">Loading coupons...</div>' +
    '<div id="coupons-list" class="coupons-list" style="display:none;"></div>' +
    '</div>' +
    '</div>';

// Run builds
await buildApp({
    entry: 'src/mcp/ui/revenue/app/main.ts',
    out: 'src/mcp/ui/revenue/generated/dashboard-html.ts',
    marker: 'freemius-revenue-dashboard',
    title: 'Freemius Revenue',
    css: REVENUE_CSS,
    bodyHtml: REVENUE_BODY,
    variableName: 'revenueDashboardHtml',
});

await buildApp({
    entry: 'src/mcp/ui/coupon/app/main.ts',
    out: 'src/mcp/ui/coupon/generated/coupon-form-html.ts',
    marker: 'freemius-coupon-form',
    title: 'Create Coupon',
    css: COUPON_CSS,
    bodyHtml: COUPON_BODY,
    variableName: 'freemiusCouponFormHtml',
});

const CUSTOMER_CSS = [
    ':root{--bg-gradient:linear-gradient(135deg,#0f172a 0%,#1e1b4b 100%);--card-bg:rgba(30,41,59,0.7);--card-border:rgba(255,255,255,0.08);--text-primary:#f8fafc;--text-secondary:#94a3b8;--primary:#6366f1;--primary-hover:#4f46e5;--success:#10b981;--success-bg:rgba(16,185,129,0.15);--warning:#f59e0b;--warning-bg:rgba(245,158,11,0.15);--error:#ef4444;--error-bg:rgba(239,68,68,0.15);--border-radius:16px;--font-sans:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}',
    '@media (prefers-color-scheme:light){:root{--bg-gradient:linear-gradient(135deg,#f1f5f9 0%,#e2e8f0 100%);--card-bg:rgba(255,255,255,0.8);--card-border:rgba(0,0,0,0.08);--text-primary:#0f172a;--text-secondary:#475569;--primary:#4f46e5;--primary-hover:#3730a3;--success:#059669;--success-bg:rgba(5,150,105,0.1);--warning:#d97706;--warning-bg:rgba(217,119,6,0.1);--error:#dc2626;--error-bg:rgba(220,38,38,0.1)}}',
    'body{margin:0;padding:24px;font-family:var(--font-sans);background:var(--bg-gradient);color:var(--text-primary);box-sizing:border-box;display:flex;justify-content:center;align-items:flex-start}',
    '#root{width:100%;max-width:720px}',
    '.profile-card{background:var(--card-bg);border:1px solid var(--card-border);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border-radius:var(--border-radius);padding:28px;box-shadow:0 8px 32px 0 rgba(0,0,0,0.2);box-sizing:border-box;width:100%}',
    '.profile-header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid var(--card-border);padding-bottom:20px;margin-bottom:24px;gap:16px}',
    '.user-identity{display:flex;flex-direction:column}',
    '.user-name{font-size:24px;font-weight:700;margin:0 0 4px 0}',
    '.user-email{font-size:14px;color:var(--text-secondary);margin:0}',
    '.user-meta-right{text-align:right;display:flex;flex-direction:column;align-items:flex-end}',
    '.country-badge{display:inline-flex;align-items:center;gap:6px;background:rgba(128,128,128,0.1);padding:4px 10px;border-radius:20px;font-size:12px;font-weight:600;border:1px solid var(--card-border)}',
    '.member-since{font-size:12px;color:var(--text-secondary);margin-top:8px}',
    '.user-id{font-family:monospace;font-size:11px;background:rgba(128,128,128,0.15);padding:2px 6px;border-radius:4px;margin-top:4px}',
    '.metrics-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:28px}',
    '.metric-card{background:rgba(128,128,128,0.05);border:1px solid var(--card-border);border-radius:12px;padding:16px;text-align:center}',
    '.metric-value{font-size:20px;font-weight:700;margin-top:4px;word-break:break-all}',
    '.metric-label{font-size:11px;color:var(--text-secondary);text-transform:uppercase;letter-spacing:0.5px}',
    '.tabs-nav{display:flex;gap:8px;border-bottom:1px solid var(--card-border);margin-bottom:20px}',
    '.tab-btn{background:none;border:none;padding:10px 16px;font-size:14px;font-weight:600;color:var(--text-secondary);cursor:pointer;position:relative}',
    '.tab-btn:hover{color:var(--text-primary)}',
    '.tab-btn.active{color:var(--primary)}',
    '.tab-btn.active::after{content:"";position:absolute;bottom:-1px;left:0;right:0;height:2px;background:var(--primary)}',
    '.tab-content{min-height:200px}',
    '.tab-panel{display:none}',
    '.tab-panel.active{display:block;animation:fadeIn 0.25s ease-out}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}',
    '.list-item{background:rgba(128,128,128,0.03);border:1px solid var(--card-border);border-radius:10px;padding:14px 16px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;font-size:14px}',
    '.list-item:last-child{margin-bottom:0}',
    '.item-left{display:flex;flex-direction:column;gap:4px}',
    '.item-title{font-weight:600}',
    '.item-subtitle{font-size:12px;color:var(--text-secondary)}',
    '.item-right{text-align:right;display:flex;flex-direction:column;align-items:flex-end;gap:6px}',
    '.badge{font-size:11px;font-weight:600;padding:3px 8px;border-radius:12px;text-transform:capitalize}',
    '.badge.active,.badge.success,.badge.paid{background:var(--success-bg);color:var(--success)}',
    '.badge.pending,.badge.trialing,.badge.trial,.badge.warning{background:var(--warning-bg);color:var(--warning)}',
    '.badge.cancelled,.badge.failed,.badge.expired,.badge.error,.badge.inactive{background:var(--error-bg);color:var(--error)}',
    '.empty-state{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:40px 20px;color:var(--text-secondary);text-align:center}',
    '.empty-icon{font-size:32px;margin-bottom:12px;opacity:0.5}',
    '.shimmer{background:linear-gradient(90deg,rgba(128,128,128,0.05) 25%,rgba(128,128,128,0.12) 50%,rgba(128,128,128,0.05) 75%);background-size:200% 100%;animation:shimmer-anim 1.5s infinite}',
    '@keyframes shimmer-anim{0%{background-position:200% 0}100%{background-position:-200% 0}}',
    '.shimmer-block{height:16px;border-radius:4px;margin-bottom:8px}',
].join('');

const CUSTOMER_BODY =
    '<main id="root" class="profile-card"><div class="empty-state"><div class="empty-icon">⏳</div><div>Loading customer details...</div></div></main>';

await buildApp({
    entry: 'src/mcp/ui/customer/app/main.ts',
    out: 'src/mcp/ui/customer/generated/profile-html.ts',
    marker: 'freemius-customer-profile',
    title: 'Customer Profile',
    css: CUSTOMER_CSS,
    bodyHtml: CUSTOMER_BODY,
    variableName: 'freemiusCustomerProfileHtml',
});
