// build-ui.ts — bundle the revenue-dashboard iframe app (target:browser) into ONE self-contained
// HTML string, emitted as a GENERATED TS module the MCP bin imports. Run: `bun run generate:ui`.
// Generated (not a dist/ file read): no runtime path resolution, no build-order race with build.ts —
// it is a normal source import bundled into the bin.

const APP_ENTRY = 'src/mcp/ui/revenue/app/main.ts';
const OUT = 'src/mcp/ui/revenue/generated/dashboard-html.ts';
const MARKER = 'freemius-revenue-dashboard';

const CSS = [
    ':root{color-scheme:light dark;font-family:system-ui,sans-serif}',
    'body{margin:0;padding:16px;line-height:1.4}',
    'nav.windows{display:flex;gap:8px;margin-bottom:12px}',
    'nav.windows button{padding:4px 12px;border-radius:6px;border:1px solid currentColor;background:transparent;cursor:pointer;font:inherit}',
    'header .window{font-size:12px;opacity:.7}',
    'p.flags{color:#b45309;font-size:13px;margin:8px 0}',
    'p.empty{opacity:.6}',
    '.cards{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}',
    '.card{border:1px solid rgba(128,128,128,.3);border-radius:10px;padding:12px 14px}',
    '.card h2{margin:0 0 10px;font-size:16px}.card h2 small{opacity:.6;font-weight:400;font-size:12px}',
    '.bar-row{display:grid;grid-template-columns:64px 1fr 80px;align-items:center;gap:8px;margin:4px 0;font-size:13px}',
    '.bar{height:8px;background:rgba(128,128,128,.18);border-radius:4px;overflow:hidden}',
    '.bar-fill{display:block;height:100%}',
    '.bar-fill.gross{background:#2563eb}.bar-fill.refunds{background:#dc2626}.bar-fill.net{background:#16a34a}',
    '.bar-val{text-align:right;font-variant-numeric:tabular-nums}',
].join('');

const result = await Bun.build({
    entrypoints: [APP_ENTRY],
    target: 'browser',
    format: 'esm',
    minify: true,
});
if (!result.success) {
    for (const log of result.logs) {
        console.error(log);
    }
    process.exit(1);
}

const js = await result.outputs[0]!.text();

const html =
    '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    `<title>Freemius Revenue</title><style>${CSS}</style></head>` +
    `<body data-app="${MARKER}">` +
    '<nav class="windows"><button data-days="30">30d</button>' +
    '<button data-days="90">90d</button><button data-days="365">365d</button></nav>' +
    '<main id="root"><p class="empty">Loading…</p></main>' +
    `<script type="module">${js}</script></body></html>`;

const banner =
    '// GENERATED by scripts/build-ui.ts — DO NOT EDIT. Run `bun run generate:ui` to regenerate.\n' +
    '// The self-contained revenue-dashboard MCP App (HTML + inlined, minified, browser-bundled JS).\n';

await Bun.write(OUT, `${banner}export const revenueDashboardHtml = ${JSON.stringify(html)};\n`);
console.log(`Wrote ${OUT} (${html.length} bytes)`);
