// build-ui.ts — bundle the iframe apps (target:browser) into self-contained HTML strings,
// emitted as GENERATED TS modules that the MCP server imports. Run: `bun run generate:ui`.

async function buildApp(options: {
    entry: string;
    out: string;
    marker: string;
    title: string;
    css: string;
    bodyHtml: string;
    variableName: string;
}) {
    const result = await Bun.build({
        entrypoints: [options.entry],
        target: 'browser',
        format: 'esm',
        minify: true,
    });
    if (!result.success) {
        for (const log of result.logs) {
            console.error(log);
        }
        process.exit(1);
    }

    const output = result.outputs[0];
    if (!output) {
        throw new Error(`No build output found for ${options.entry}`);
    }
    const js = await output.text();

    const html =
        '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
        '<meta name="viewport" content="width=device-width,initial-scale=1">' +
        `<title>${options.title}</title><style>${options.css}</style></head>` +
        `<body data-app="${options.marker}">` +
        options.bodyHtml +
        `<script type="module">${js}</script></body></html>`;

    const banner =
        '// GENERATED by scripts/build-ui.ts — DO NOT EDIT. Run `bun run generate:ui` to regenerate.\n' +
        `// The self-contained ${options.title} MCP App (HTML + inlined, minified, browser-bundled JS).\n`;

    await Bun.write(options.out, `${banner}export const ${options.variableName} = ${JSON.stringify(html)};\n`);
    console.log(`Wrote ${options.out} (${html.length} bytes)`);
}

// --- Revenue Dashboard Config ---
const REVENUE_CSS = [
    ':root{color-scheme:light dark;font-family:system-ui,sans-serif}',
    'body{margin:0;padding:16px;line-height:1.4}',
    'nav.windows{display:flex;gap:8px;margin-bottom:12px}',
    'nav.windows button{padding:4px 12px;border-radius:6px;border:1px solid currentColor;background:transparent;cursor:pointer;font:inherit}',
    'header .window{font-size:12px;opacity:.7}',
    'p.flags{color:#b45309;font-size:13px;margin:8px 0}',
    'p.empty{opacity:.6}',
    '.cards{display:grid;gap:16px;grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}',
    '.card{border:1px solid rgba(128,128,128,.3);border-radius:10px;padding:12px 14px}',
    '.card h2{margin:0 0 10px;font-size:16px}.card h2 small{opacity:.6;font-weight:400;font-size:12px}',
    '.bar-row{display:grid;grid-template-columns:64px 1fr 80px;align-items:center;gap:8px;margin:4px 0;font-size:13px}',
    '.bar{height:8px;background:rgba(128,128,128,.18);border-radius:4px;overflow:hidden}',
    '.bar-fill{display:block;height:100%}',
    '.bar-fill.gross{background:#2563eb}.bar-fill.refunds{background:#dc2626}.bar-fill.net{background:#16a34a}',
    '.bar-val{text-align:right;font-variant-numeric:tabular-nums}',
].join('');

const REVENUE_BODY =
    '<nav class="windows"><button data-days="30">30d</button>' +
    '<button data-days="90">90d</button><button data-days="365">365d</button></nav>' +
    '<main id="root"><p class="empty">Loading…</p></main>';

// --- Coupon Form Config ---
const COUPON_CSS = [
    ':root{color-scheme:light dark;font-family:system-ui,-apple-system,sans-serif;',
    '--bg:#121214;--card-bg:#1c1c1f;--border:rgba(255,255,255,0.1);',
    '--text:#f3f4f6;--text-muted:#9ca3af;--primary:#3b82f6;--primary-hover:#2563eb;',
    '--success:#10b981;--error:#ef4444}',
    '@media (prefers-color-scheme:light){:root{',
    '--bg:#f9fafb;--card-bg:#ffffff;--border:rgba(0,0,0,0.1);',
    '--text:#111827;--text-muted:#6b7280;--primary:#2563eb;--primary-hover:#1d4ed8}}',
    'body{margin:0;padding:16px;background-color:var(--bg);color:var(--text);',
    'display:flex;justify-content:center;align-items:flex-start;min-height:100vh}',
    '.coupon-form-card{background:var(--card-bg);border:1px solid var(--border);',
    'border-radius:12px;padding:24px;width:100%;max-width:480px;',
    'box-shadow:0 4px 6px -1px rgba(0,0,0,0.1),0 2px 4px -1px rgba(0,0,0,0.06);box-sizing:border-box}',
    'h2{margin:0 0 20px;font-size:20px;font-weight:600}',
    '.form-group{margin-bottom:16px}',
    '.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}',
    'label{display:block;font-size:13px;font-weight:500;margin-bottom:6px;color:var(--text-muted)}',
    'input[type="text"],input[type="number"],select{width:100%;padding:10px 12px;',
    'border-radius:6px;border:1px solid var(--border);background:var(--card-bg);',
    'color:var(--text);font-family:inherit;font-size:14px;box-sizing:border-box;',
    'transition:border-color 0.15s ease,box-shadow 0.15s ease}',
    'input:focus,select:focus{outline:none;border-color:var(--primary);',
    'box-shadow:0 0 0 3px rgba(59,130,246,0.15)}',
    '.plans-status{font-size:13px;color:var(--text-muted);font-style:italic;padding:4px 0}',
    '.plans-checkboxes{max-height:150px;overflow-y:auto;border:1px solid var(--border);',
    'border-radius:6px;padding:8px 12px;display:flex;flex-direction:column;gap:8px}',
    '.plan-option{display:flex;align-items:center;gap:8px;font-size:14px;color:var(--text);cursor:pointer}',
    '.plan-option input{margin:0;cursor:pointer}',
    'button[type="submit"]{width:100%;padding:12px;border:none;border-radius:6px;',
    'background-color:var(--primary);color:white;font-size:14px;font-weight:600;',
    'cursor:pointer;transition:background-color 0.15s ease;margin-top:8px}',
    'button[type="submit"]:hover:not(:disabled){background-color:var(--primary-hover)}',
    'button[type="submit"]:disabled{opacity:0.6;cursor:not-allowed}',
    '.result{margin-top:16px;padding:12px;border-radius:6px;font-size:14px;display:none;animation:fadeIn 0.2s ease-in-out}',
    '.result.success{background:rgba(16, 185, 129, 0.1);border:1px solid var(--success);color:var(--success)}',
    '.result.error{background:rgba(239, 68, 68, 0.1);border:1px solid var(--error);color:var(--error)}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}',
].join('');

const COUPON_BODY =
    '<form id="coupon-form" class="coupon-form-card">' +
    '<h2>Create Coupon</h2>' +
    '<div class="form-group">' +
    '<label for="code">Coupon Code</label>' +
    '<input type="text" id="code" name="code" placeholder="e.g., SAVE50" required autocomplete="off" />' +
    '</div>' +
    '<div class="form-row">' +
    '<div class="form-group">' +
    '<label for="discount">Discount Amount</label>' +
    '<input type="number" id="discount" name="discount" step="any" min="0" placeholder="0" required />' +
    '</div>' +
    '<div class="form-group">' +
    '<label for="discount-type">Discount Type</label>' +
    '<select id="discount-type" name="discount_type">' +
    '<option value="percentage">Percentage (%)</option>' +
    '<option value="dollar">Dollar ($)</option>' +
    '</select>' +
    '</div>' +
    '</div>' +
    '<div class="form-group">' +
    '<label>Applies to Plans</label>' +
    '<div id="plans-loading" class="plans-status">Loading plans...</div>' +
    '<div id="plans-container" class="plans-checkboxes"></div>' +
    '</div>' +
    '<button type="submit" id="submit-btn">Create Coupon</button>' +
    '<div id="result" class="result"></div>' +
    '</form>';

// Run builds
await buildApp({
    entry: 'src/mcp/ui/revenue/app/main.ts',
    out: 'src/mcp/ui/revenue/generated/dashboard-html.ts',
    marker: 'freemius-revenue-dashboard',
    title: 'Freemius Revenue',
    css: REVENUE_CSS,
    bodyHtml: REVENUE_BODY,
    variableName: 'revenueDashboardHtml',
});

await buildApp({
    entry: 'src/mcp/ui/coupon/app/main.ts',
    out: 'src/mcp/ui/coupon/generated/coupon-form-html.ts',
    marker: 'freemius-coupon-form',
    title: 'Create Coupon',
    css: COUPON_CSS,
    bodyHtml: COUPON_BODY,
    variableName: 'freemiusCouponFormHtml',
});
