// generate.ts — regenerate the committed codegen artifacts from openapi.yaml (docs/specs §9):
//   src/core/catalog.ts   — the operation catalog (id/method/templatePath/scope/safe/destructive/params)
//   src/core/schema.d.ts  — compile-time types via openapi-typescript
//
// Run `bun run fetch-spec` first to refresh openapi.yaml. Both artifacts are committed so installs
// need no codegen. Catalog metadata is DERIVED (safe = GET, destructive = DELETE + overlay), so there
// is no hand-classified per-op overlay to drift.

import { readFileSync, writeFileSync } from 'node:fs';
import { $ } from 'bun';
import { buildCatalog } from './lib/build-catalog.js';

const SPEC = 'openapi.yaml';

const doc = Bun.YAML.parse(readFileSync(SPEC, 'utf8')) as Parameters<typeof buildCatalog>[0];
const catalog = buildCatalog(doc);

const catalogFile = `// catalog.ts — GENERATED by scripts/generate.ts from openapi.yaml. DO NOT EDIT BY HAND.
// ${catalog.length} operations. Regenerate with \`bun run generate\`.

import type { CatalogEntry } from './catalog-types.js';

export const catalog: readonly CatalogEntry[] = ${JSON.stringify(catalog, null, 2)};
`;
writeFileSync('src/core/catalog.ts', catalogFile);
console.log(`Wrote src/core/catalog.ts (${catalog.length} operations)`);

await $`bunx openapi-typescript ${SPEC} -o src/core/schema.d.ts`;
console.log('Wrote src/core/schema.d.ts');
